force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case Config</label>
    <nameField>
        <displayFormat>CaseConfig-{0000}</displayFormat>
        <label>Case Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>Config-{0000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CK_ConfigsController.cls
public with sharing class CK_ConfigsController {

    @AuraEnabled(cacheable=true)
    public static Wrapper getAvailableConfigs(){
        try {
            List<Config__c> lstConfigs = [SELECT Id, Label__c, Amount__c, Type__c FROM Config__c ORDER BY Name];
            Integer count = [SELECT Count() FROM Config__c];
            return new Wrapper(count, lstConfigs);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class Wrapper {
        @AuraEnabled
        public Integer count;
        @AuraEnabled
        public List<Config__c> lstConfigs = new List<Config__c>();

        public Wrapper(Integer count, List<Config__c> lstConfigs){
            this.count = count;
            this.lstConfigs = lstConfigs;
        }
    }

    @AuraEnabled
    public static DataTransferObjects.OperationResult createCaseConfigs(String caseId, List<Config__c> lstSelectedConfigs){
        List<String> lstValidations = new List<String>();
        try {
            List<Case_Config__c> lstCaseConfigs = new List<Case_Config__c>();
            for(Config__c eachConfig : lstSelectedConfigs){
                Case_Config__c eachCaseConfig = new Case_Config__c();
                eachCaseConfig.Label__c = eachConfig.Label__c;
                eachCaseConfig.Type__c = eachConfig.Type__c;
                eachCaseConfig.Amount__c = eachConfig.Amount__c;
                eachCaseConfig.Case__c = caseId;
                lstCaseConfigs.add(eachCaseConfig);
            }

            if(!lstCaseConfigs.isEmpty()){
                Database.SaveResult[] srList = Database.insert(lstCaseConfigs, false);
                Integer count = 0;
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        count++;
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            lstValidations.add(err.getMessage());
                        }
                    }
                }
                if(count == 0){
                    return new DataTransferObjects.OperationResult(false,lstValidations);
                }
                return new DataTransferObjects.OperationResult(true);
            }
            lstValidations.add('Something failed. Please contact your System Admin!');
            return new DataTransferObjects.OperationResult(false,lstValidations);
        } catch (Exception exc) {
            lstValidations.add(exc.getMessage());
            return new DataTransferObjects.OperationResult(false,lstValidations);
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Case_Config__c> getCaseConfigs(String caseId){
        try {
            List<Case_Config__c> lstCaseConfigs = [SELECT Id, Label__c, Amount__c, Type__c FROM Case_Config__c WHERE Case__c = :caseId ORDER BY Name];
            return lstCaseConfigs;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static DataTransferObjects.OperationResult sendRequest(String caseId, String payload){
        List<String> lstValidations = new List<String>();
        try {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('callout:RequestCatcherClark');
            request.setMethod('POST');     
            request.setBody(payload);
            HttpResponse response = http.send(request);
            
            if (response.getStatusCode() == 200) {
                String resBody = response.getbody();
                String jsonStr = resBody.replaceAll( '\\s+', ''); //Before parsing the JSON string, I have removed the space.
                system.debug('resBody '+resBody);

                Case eachCase = new Case();
                eachCase.Id = caseId;
                eachCase.Status = 'Closed';
                update eachCase;

                return new DataTransferObjects.OperationResult(true);
            }
            else {
                lstValidations.add('Information could not be posted to the server. Please contact your System Admin.');
                return new DataTransferObjects.OperationResult(false,lstValidations);
            }
        } catch (Exception exc) {
            lstValidations.add(exc.getMessage());
            return new DataTransferObjects.OperationResult(false,lstValidations);
        }
    }
}